# Generated by Django 4.1.3 on 2022-11-25 19:45

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('geo_info', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('language', models.CharField(choices=[('EN', 'EN'), ('FR', 'FR'), ('ES', 'ES')], default='EN', max_length=5)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], default='EN', max_length=5)),
                ('service_area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polygons.servicearea')),
            ],
        ),
    ]
