# Generated by Django 4.1.3 on 2022-11-26 06:41

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='service_area',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='polygons.servicearea'),
        ),
    ]
